[user]
name = "mei"
email = "konecho@outlook.com"
groups = ["wheel", "input", "networkmanager", "video"]
# mkpasswd -m sha-512
password = "$6$uiElHlBCyxUEkWFo$FqTxpsOFPhU0ak3V9.xGTvHblsRxQOffE6zfUGJMflt9B.11NqiokVB.yETtBU0hJn5Z.SNS6IFrlUj6hToAO/"

[pkgs]
unfree = [
  "dyalog",
  "segger-jlink",
  "nrfconnect",
  "corefonts",                           # onlyoffice
  "vista-fonts",
  "vista-fonts-chs",
  "android-studio-stable",
  "microsoft-edge-stable",
  "google-chrome",
  "vivaldi",
  "vscode",
  "wechat-uos",
  "obsidian",
  "unrar",
  "libsciter",                           # rustdesk
  "steam-runtime",
  "steam-original",
  "steam",
  "steam-unwrapped",
  "steam-run",
  "steamcmd",
  "fcitx5-chinese-addons",
  "fcitx5-pinyin-moegirl",
  "fcitx5-pinyin-minecraft",
  "vscode-extension-mhutchie-git-graph",
  "vscode-extension-visualjj-visualjj",
]
insecure = [
  # "libxls-1.6.2",
  # "electron-25.9.0", # obsidian
  # "nodejs-16.20.1", # code-server
  # "electron-19.0.7",
  # "electron-12.2.3",
  # "openssl-1.1.1u",
]
